reset;
model Swimplex_time.mod;
data test_data.dat;

option solver "gurobi";

objective AdversaryResponse;
solve;

display placement_solo;
display placement;
display placement_med;

# Fix away teams to their solved values
fix {t in Adversary, a in AthletesTeam[t], e in SoloEvents} athlete_swims_event_solo[a,e];
fix {t in Adversary, a in AthletesTeam[t], e in RelayEvents, l in Level} athlete_swims_event_rel[a,e,l];
fix {t in Adversary, a in AthletesTeam[t], e in MedleyEvents, l in Level, s in Stroke} athlete_swims_event_med[a,e,l,s];
fix {t in Adversary, a in AthletesTeam[t], e in DivingEvents} athlete_dives_event[a,e];

unfix {a in AthletesTeam[home_team], e in SoloEvents} athlete_swims_event_solo[a,e];
unfix {a in AthletesTeam[home_team], e in RelayEvents, l in Level} athlete_swims_event_rel[a,e,l];
unfix {a in AthletesTeam[home_team], e in MedleyEvents, l in Level, s in Stroke} athlete_swims_event_med[a,e,l,s];
unfix {a in AthletesTeam[home_team], e in DivingEvents} athlete_dives_event[a,e];

objective TotalPoints;
solve;

display placement_solo;
display placement;
display placement_med;
