#!/usr/bin/env python3
"""
ampl_export.py — Convert best_performances_<gender>.json to AMPL .dat format.

Usage:
    python3 ampl_export.py --season 2025-26 --gender Men
    python3 ampl_export.py --season 2025-26 --gender Women

Output:
    data/<season>/best_performances_<gender>.dat
"""

import argparse
import json
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"

# AMPL id → JSON event key
IND_EVENTS: dict[str, str] = {
    "free50":    "50 Yard Freestyle",
    "free100":   "100 Yard Freestyle",
    "free200":   "200 Yard Freestyle",
    "free500":   "500 Yard Freestyle",
    "free1650":  "1650 Yard Freestyle",
    "back100":   "100 Yard Backstroke",
    "back200":   "200 Yard Backstroke",
    "breast100": "100 Yard Breaststroke",
    "breast200": "200 Yard Breaststroke",
    "fly100":    "100 Yard Butterfly",
    "fly200":    "200 Yard Butterfly",
    "im200":     "200 Yard IM",
    "im400":     "400 Yard IM",
}

RELAY_EVENTS: dict[str, str] = {
    "relay_free50":   "50 Yard Freestyle (Relay Split)",
    "relay_free100":  "100 Yard Freestyle (Relay Split)",
    "relay_free200":  "200 Yard Freestyle (Relay Split)",
    "relay_back50":   "50 Yard Backstroke (Relay Split)",
    "relay_breast50": "50 Yard Breaststroke (Relay Split)",
    "relay_fly50":    "50 Yard Butterfly (Relay Split)",
    "relay_breast100":"100 Yard Breaststroke (Relay Split)",
    "relay_fly100":   "100 Yard Butterfly (Relay Split)",
}

ALL_EVENTS: dict[str, str] = {**IND_EVENTS, **RELAY_EVENTS}


def parse_time(s: str, sentinel: float = 9999.0) -> float:
    s = s.strip()
    # Strip "NT x" prefix (no-time marker)
    if s.startswith("NT x"):
        s = s[4:].strip()
    if ":" in s:
        m, rest = s.split(":", 1)
        try:
            return int(m) * 60 + float(rest)
        except ValueError:
            return sentinel
    try:
        return float(s)
    except ValueError:
        return sentinel


def format_time(val: float, sentinel: float) -> str:
    if val == sentinel:
        return f"{int(sentinel)}"
    return f"{val:.2f}"


def write_dat(
    out_path: Path,
    season: str,
    gender: str,
    athletes: list[str],
    times: dict[str, dict[str, float]],
    sentinel: float,
) -> None:
    all_event_ids = list(ALL_EVENTS.keys())
    ind_ids = list(IND_EVENTS.keys())
    rel_ids = list(RELAY_EVENTS.keys())

    lines: list[str] = []
    lines.append(f"# AMPL data file — SCIAC best performances {season} {gender}")
    lines.append("# Generated by ampl_export.py")
    lines.append("")

    # IND_EVENTS set
    lines.append("set IND_EVENTS :=")
    lines.append("  " + "  ".join(ind_ids) + " ;")
    lines.append("")

    # RELAY_EVENTS set
    lines.append("set RELAY_EVENTS :=")
    lines.append("  " + "  ".join(rel_ids) + " ;")
    lines.append("")

    lines.append("set EVENTS := IND_EVENTS union RELAY_EVENTS ;")
    lines.append("")

    # ATHLETES set — one name per line for readability
    lines.append("set ATHLETES :=")
    for name in athletes:
        lines.append(f"  '{name}'")
    lines.append("  ;")
    lines.append("")

    # param times — column-aligned table
    # Compute column widths
    col_widths = {eid: max(len(eid), 7) for eid in all_event_ids}
    for name in athletes:
        for eid in all_event_ids:
            val = times[name][eid]
            col_widths[eid] = max(col_widths[eid], len(format_time(val, sentinel)))

    name_width = max(len(f"'{n}'") for n in athletes) if athletes else 10

    # Header row
    header = "param times :"
    header_pad = " " * (name_width - len("param times :") + 2)
    col_headers = "  ".join(eid.ljust(col_widths[eid]) for eid in all_event_ids)
    lines.append(f"param times :{header_pad}{col_headers}  :=")

    # Data rows
    for name in athletes:
        quoted = f"'{name}'"
        row_vals = "  ".join(
            format_time(times[name][eid], sentinel).rjust(col_widths[eid])
            for eid in all_event_ids
        )
        lines.append(f"{quoted.ljust(name_width)}  {row_vals}")

    lines.append(";")
    lines.append("")

    out_path.write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Export best_performances JSON to AMPL .dat format"
    )
    ap.add_argument("--season", required=True, metavar="YYYY-YY")
    ap.add_argument("--gender", required=True, choices=["Men", "Women", "Mixed"])
    ap.add_argument(
        "--sentinel", type=float, default=9999.0,
        help="Value to use for missing/unparseable times (default: 9999)"
    )
    args = ap.parse_args()

    in_path = DATA_DIR / args.season / f"best_performances_{args.gender.lower()}.json"
    if not in_path.exists():
        ap.error(
            f"Input not found: {in_path}\n"
            f"Run:  python3 best_performances.py --season {args.season} --gender {args.gender}"
        )

    data = json.loads(in_path.read_text())
    swimmers_raw = data["swimmers"]

    # Filter to swimmers only, sort alphabetically
    athletes = sorted(
        name for name, info in swimmers_raw.items()
        if info.get("type") == "swimmer"
    )

    # Build times matrix
    times: dict[str, dict[str, float]] = {}
    for name in athletes:
        events_json = swimmers_raw[name]["events"]
        times[name] = {}
        for eid, json_key in ALL_EVENTS.items():
            entry = events_json.get(json_key)
            if entry is None:
                times[name][eid] = args.sentinel
            else:
                times[name][eid] = parse_time(entry["best"], args.sentinel)

    out_path = DATA_DIR / args.season / f"best_performances_{args.gender.lower()}.dat"
    write_dat(out_path, args.season, args.gender, athletes, times, args.sentinel)

    n_missing = sum(
        1 for name in athletes
        for eid in ALL_EVENTS
        if times[name][eid] == args.sentinel
    )
    n_total = len(athletes) * len(ALL_EVENTS)
    print(f"Written: {out_path}")
    print(f"  {len(athletes)} athletes × {len(ALL_EVENTS)} events = {n_total} cells")
    print(f"  {n_missing} sentinel ({args.sentinel}) values ({n_missing/n_total*100:.1f}% missing)")


if __name__ == "__main__":
    main()
